In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 전체 코드 출력
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [3]:
# 한글 문제
# matplotlit의 기본 폰트에서 한글 지원되지 않기 때문에
# matplotlib의 폰트 변경 필요
import platform

from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':  # 맥OS 
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':  # 윈도우
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system...  sorry~~~')

In [4]:
# header : 엑셀파일에서 몇번째 행을 여기로 불러올때 열제목으로 사용할 것인가 
school_data = pd.read_excel('../Data/학교_Data/1.+유·초·중등교육기관+주소록(2019).xlsx', header=3)
school_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21332 entries, 0 to 21331
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   연도        21332 non-null  int64
 1   학제        21332 non-null  object
 2   학교 세부 유형  21332 non-null  object
 3   고등학교유형    2360 non-null   object
 4   시도        21332 non-null  object
 5   교육지원청     21332 non-null  object
 6   행정구       21332 non-null  object
 7   학교명       21332 non-null  object
 8   본분교       21332 non-null  object
 9   학교상태      21332 non-null  object
 10  설립        21332 non-null  object
 11  남여공학      5861 non-null   object
 12  우편번호      21332 non-null  object
 13  도로명주소     21332 non-null  object
 14  연락처       21332 non-null  object
 15  팩스번호      21332 non-null  object
 16  홈페이지      20357 non-null  object
dtypes: int64(1), object(16)
memory usage: 2.8+ MB

In [5]:
# drop : 필요없는 열을 제거하기 위한 함수. 다만 실제 DF에는 적용 안됨.  적용시키려면 inplace =True 사용
# columns : 이걸 사용해야 열 번호로 지정가능 아니면 한글로 쳐야됨 ['학교명', '학교상태',..]
school_data.drop(school_data.columns[[0,10,11,14,15,16]],axis=1, inplace=True)

In [6]:
school_data.head()

,학제,학교 세부 유형,고등학교유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소
0,유치원,유치원,NaN,서울,중부,종로구,린덴바움유치원,본교,기존(원)교,030-25,서울특별시 종로구 통일로12길 51 . 린덴바움유치원 (무악동)
1,유치원,유치원,NaN,서울,중부,종로구,배화여자대학교 부속 배화유치원,본교,기존(원)교,030-39,서울특별시 종로구 필운대로1길 34 (필운동)
2,유치원,유치원,NaN,서울,중부,종로구,봄샘유치원,본교,기존(원)교,031-24,서울특별시 종로구 율곡로 264 (종로6가)
3,유치원,유치원,NaN,서울,중부,종로구,상명사대부속유치원,본교,기존(원)교,030-15,서울특별시 종로구 홍지문2길 1 (홍지동)
4,유치원,유치원,NaN,서울,중부,종로구,서울명신초등학교병설유치원,본교,기존(원)교,030-93,서울특별시 종로구 낙산길 250 (창신동. 서울명신초등학교)

In [59]:
# 다른 테이블과 연결시키기 위해(법정동명) 도로명 주소에서 구까지 추출.
# 도로명 주소에서 스페이스 단위로 자른후 앞 두개 가져와 ind에 저장후 법정동이라는 새로운 컬럼 만듬
ind=[]
for i in range(len(school_data)):
    if school_data['도로명주소'][i].split(' ')[0]== '세종특별자치시' :
        ind.append(school_data['도로명주소'][i].split(' ')[0])
    elif school_data['도로명주소'][i].split(' ')[0]== '서울' :
         ind.append('서울특별시 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '경기' :
         ind.append('경기도 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '경남' :
         ind.append('경상남도 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '대구' :
         ind.append('대구광역시 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '충북' :
         ind.append('충청북도 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '인천' :
         ind.append('인천광역시 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '강원' :
         ind.append('강원도 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '경북' :
         ind.append('경상북도 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '전북' :
         ind.append('전라북도 ' +school_data['도로명주소'][i].split(' ')[1])
    else :
        ind.append(' '.join(school_data['도로명주소'][i].split(' ')[:2]))

school_data['법정동']=ind
school_data

,학제,학교 세부 유형,고등학교유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소,법정동
0,유치원,유치원,NaN,서울,중부,종로구,린덴바움유치원,본교,기존(원)교,030-25,서울특별시 종로구 통일로12길 51 . 린덴바움유치원 (무악동),서울특별시 종로구
1,유치원,유치원,NaN,서울,중부,종로구,배화여자대학교 부속 배화유치원,본교,기존(원)교,030-39,서울특별시 종로구 필운대로1길 34 (필운동),서울특별시 종로구
2,유치원,유치원,NaN,서울,중부,종로구,봄샘유치원,본교,기존(원)교,031-24,서울특별시 종로구 율곡로 264 (종로6가),서울특별시 종로구
3,유치원,유치원,NaN,서울,중부,종로구,상명사대부속유치원,본교,기존(원)교,030-15,서울특별시 종로구 홍지문2길 1 (홍지동),서울특별시 종로구
4,유치원,유치원,NaN,서울,중부,종로구,서울명신초등학교병설유치원,본교,기존(원)교,030-93,서울특별시 종로구 낙산길 250 (창신동. 서울명신초등학교),서울특별시 종로구
...,...,...,...,...,...,...,...,...,...,...,...,...
21327,각종학교,각종학교(고교),NaN,경남,경남,창원시,창원예술학교,본교,기존(원)교,512-03,경상남도 창원시 마산회원구 구암북12길 24 (구암동),경상남도 창원시
21328,각종학교,각종학교(중학),NaN,경남,경남,진주시,경남꿈키움중학교,본교,기존(원)교,526-15,경상남도 진주시 이반성면 길성길 1-80 (이반성면),경상남도 진주시
21329,각종학교,각종학교(고교),NaN,경남,경남,밀양시,밀양영화고등학교,본교,기존(원)교,504-53,경상남도 밀양시 상남면 평촌중앙로 61-6 (상남면),경상남도 밀양시
21330,각종학교,각종학교(고교),NaN,경남,경남,고성군,경남고성음악고등학교,본교,기존(원)교,529-56,경상남도 고성군 하일면 공룡로 987 (하일면),경상남도 고성군
21331,각종학교,각종학교(중학),NaN,경남,경남,하동군,지리산중학교,본교,기존(원)교,523-09,경상남도 하동군 청암면 삼신봉로 110-8 . 지리산중학교 (청암면),경상남도 하동군

In [60]:
# 외부 법정동 테이블과 연결하려면 이름을 일치시켜야 해서 이름이 다른 것들 찾아서 하나하나 지정
school_data.loc[school_data.법정동=='경남 창원시', "법정동"] = '경상남도 창원시'
school_data.loc[school_data.법정동=='경북 영천시', "법정동"] = '경상북도 영천시'
school_data.loc[school_data.법정동=='경북 영천시', "법정동"] = '경상북도 영천시'
school_data.loc[school_data.법정동=='구로구 고척로', "법정동"] = '서울특별시 구로구'
school_data.loc[school_data.법정동=='부산 사상구', "법정동"] = '부산광역시 사상구'
school_data.loc[school_data.법정동=='서울시 구로구', "법정동"] = '서울특별시 구로구'
school_data.loc[school_data.법정동=='익산시 평동로', "법정동"] = '전라북도 익산시'
school_data.loc[school_data.법정동=='인천광역시 남구', "법정동"] = '인천광역시 미추홀구'
school_data.loc[school_data.법정동=='화성시 향남읍', "법정동"] = '경기도 화성시'
school_data.loc[school_data.법정동=='경남 사천시', "법정동"] = '경상남도 사천시'
school_data.loc[school_data.법정동=='광주 광산구', "법정동"] = '광주광역시 광산구'
school_data.loc[school_data.법정동== '전남 장성군', "법정동"] = '전라남도 장성군'

In [61]:
school_data

,학제,학교 세부 유형,고등학교유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소,법정동
0,유치원,유치원,NaN,서울,중부,종로구,린덴바움유치원,본교,기존(원)교,030-25,서울특별시 종로구 통일로12길 51 . 린덴바움유치원 (무악동),서울특별시 종로구
1,유치원,유치원,NaN,서울,중부,종로구,배화여자대학교 부속 배화유치원,본교,기존(원)교,030-39,서울특별시 종로구 필운대로1길 34 (필운동),서울특별시 종로구
2,유치원,유치원,NaN,서울,중부,종로구,봄샘유치원,본교,기존(원)교,031-24,서울특별시 종로구 율곡로 264 (종로6가),서울특별시 종로구
3,유치원,유치원,NaN,서울,중부,종로구,상명사대부속유치원,본교,기존(원)교,030-15,서울특별시 종로구 홍지문2길 1 (홍지동),서울특별시 종로구
4,유치원,유치원,NaN,서울,중부,종로구,서울명신초등학교병설유치원,본교,기존(원)교,030-93,서울특별시 종로구 낙산길 250 (창신동. 서울명신초등학교),서울특별시 종로구
...,...,...,...,...,...,...,...,...,...,...,...,...
21327,각종학교,각종학교(고교),NaN,경남,경남,창원시,창원예술학교,본교,기존(원)교,512-03,경상남도 창원시 마산회원구 구암북12길 24 (구암동),경상남도 창원시
21328,각종학교,각종학교(중학),NaN,경남,경남,진주시,경남꿈키움중학교,본교,기존(원)교,526-15,경상남도 진주시 이반성면 길성길 1-80 (이반성면),경상남도 진주시
21329,각종학교,각종학교(고교),NaN,경남,경남,밀양시,밀양영화고등학교,본교,기존(원)교,504-53,경상남도 밀양시 상남면 평촌중앙로 61-6 (상남면),경상남도 밀양시
21330,각종학교,각종학교(고교),NaN,경남,경남,고성군,경남고성음악고등학교,본교,기존(원)교,529-56,경상남도 고성군 하일면 공룡로 987 (하일면),경상남도 고성군
21331,각종학교,각종학교(중학),NaN,경남,경남,하동군,지리산중학교,본교,기존(원)교,523-09,경상남도 하동군 청암면 삼신봉로 110-8 . 지리산중학교 (청암면),경상남도 하동군

In [62]:
# 유치원, 초등학교 테이블을 따로 나누기 위해 초등학교 수 카운트
school_data.groupby(['학제']).count()

,학교 세부 유형,고등학교유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소,법정동
학제,,,,,,,,,,,
각종학교,62,0,62,62,62,62,62,62,62,62,62
고등공민학교,3,0,3,3,3,3,3,3,3,3,3
고등기술학교,7,0,7,7,7,7,7,7,7,7,7
고등학교,2360,2360,2360,2360,2360,2360,2360,2360,2360,2360,2360
유치원,9139,0,9139,9139,9139,9139,9139,9139,9139,9139,9139
중학교,3251,0,3251,3251,3251,3251,3251,3251,3251,3251,3251
초등학교,6332,0,6332,6332,6332,6332,6332,6332,6332,6332,6332
특수학교,178,0,178,178,178,178,178,178,178,178,178

In [63]:
# 테이블 유치원 수에 맟추어 자르기 
s_primary = school_data.iloc[:9139,:]
s_1 = school_data.iloc[9139:,:]

In [64]:
# 테이블 마지막 유치원만 들어갔는지 확인
s_primary.tail()

,학제,학교 세부 유형,고등학교유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소,법정동
9134,유치원,유치원,NaN,제주,서귀포시,서귀포시,하원초등학교병설유치원,본교,기존(원)교,635-42,제주특별자치도 서귀포시 월평하원로 149 (하원동.하원초등학교병설유치원),제주특별자치도 서귀포시
9135,유치원,유치원,NaN,제주,서귀포시,서귀포시,한마음초등학교병설유치원,본교,기존(원)교,636-27,제주특별자치도 서귀포시 표선면 한마음초등로 408 (표선면.한마음초등학교병설유치원),제주특별자치도 서귀포시
9136,유치원,유치원,NaN,제주,서귀포시,서귀포시,해성유치원,본교,기존(원)교,635-85,제주특별자치도 서귀포시 중앙로 150번길-17 서귀포 복자성당,제주특별자치도 서귀포시
9137,유치원,유치원,NaN,제주,서귀포시,서귀포시,효돈초등학교병설유치원,본교,기존(원)교,636-06,제주특별자치도 서귀포시 효돈로 161 (신효동.효돈초등학교병설유치원),제주특별자치도 서귀포시
9138,유치원,유치원,NaN,제주,서귀포시,서귀포시,흥산초등학교병설유치원,본교,기존(원)교,636-16,제주특별자치도 서귀포시 남원읍 일주동로 6642 (남원읍.흥산초등학교병설유치원),제주특별자치도 서귀포시

In [65]:
# 필요없는 열 삭제후 실제 df 에 반영하기 위해 inplace=True 사용
s_primary.drop('고등학교유형', axis=1, inplace=True)

C:\Users\ksj14\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [66]:
# 데이터 확인
s_primary.head()

,학제,학교 세부 유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소,법정동
0,유치원,유치원,서울,중부,종로구,린덴바움유치원,본교,기존(원)교,030-25,서울특별시 종로구 통일로12길 51 . 린덴바움유치원 (무악동),서울특별시 종로구
1,유치원,유치원,서울,중부,종로구,배화여자대학교 부속 배화유치원,본교,기존(원)교,030-39,서울특별시 종로구 필운대로1길 34 (필운동),서울특별시 종로구
2,유치원,유치원,서울,중부,종로구,봄샘유치원,본교,기존(원)교,031-24,서울특별시 종로구 율곡로 264 (종로6가),서울특별시 종로구
3,유치원,유치원,서울,중부,종로구,상명사대부속유치원,본교,기존(원)교,030-15,서울특별시 종로구 홍지문2길 1 (홍지동),서울특별시 종로구
4,유치원,유치원,서울,중부,종로구,서울명신초등학교병설유치원,본교,기존(원)교,030-93,서울특별시 종로구 낙산길 250 (창신동. 서울명신초등학교),서울특별시 종로구

In [67]:
# 남은 테이블에서 초등학교 테이블 분리
s_elementary = s_1.iloc[:6332,:]
s_2= s_1.iloc[6332:,:]

In [68]:
s_elementary.tail()
s_elementary.drop('고등학교유형', axis=1, inplace=True)

,학제,학교 세부 유형,고등학교유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소,법정동
15466,초등학교,초등학교,NaN,제주,서귀포시,서귀포시,하례초등학교,본교,기존(원)교,636-13,제주특별자치도 서귀포시 남원읍 일주동로 8002 . 하례초등학교 (남원읍),제주특별자치도 서귀포시
15467,초등학교,초등학교,NaN,제주,서귀포시,서귀포시,하원초등학교,본교,기존(원)교,635-42,제주특별자치도 서귀포시 월평하원로 149 (하원동. 하원초등학교),제주특별자치도 서귀포시
15468,초등학교,초등학교,NaN,제주,서귀포시,서귀포시,한마음초등학교,본교,기존(원)교,636-27,제주특별자치도 서귀포시 표선면 한마음초등로 408 (표선면. 한마음초등학교),제주특별자치도 서귀포시
15469,초등학교,초등학교,NaN,제주,서귀포시,서귀포시,효돈초등학교,본교,기존(원)교,636-06,제주특별자치도 서귀포시 효돈로 161 (신효동),제주특별자치도 서귀포시
15470,초등학교,초등학교,NaN,제주,서귀포시,서귀포시,흥산초등학교,본교,기존(원)교,636-16,제주특별자치도 서귀포시 남원읍 일주동로 6642 . 흥산초등학교 (남원읍),제주특별자치도 서귀포시

C:\Users\ksj14\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [69]:
s_elementary.head()

,학제,학교 세부 유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소,법정동
9139,초등학교,초등학교,서울,중부,종로구,상명대학교사범대학부속초등학교,본교,기존(원)교,030-15,서울특별시 종로구 홍지문2길 1 . 상명사대부속초등학교 (홍지동.상명초등학교),서울특별시 종로구
9140,초등학교,초등학교,서울,중부,종로구,서울교동초등학교,본교,기존(원)교,031-32,서울특별시 종로구 삼일대로 446 (경운동),서울특별시 종로구
9141,초등학교,초등학교,서울,중부,종로구,서울대학교사범대학부설초등학교,본교,기존(원)교,030-87,서울특별시 종로구 대학로 64 서울대학교사범대학부설초등학교 (이화동),서울특별시 종로구
9142,초등학교,초등학교,서울,중부,종로구,서울독립문초등학교,본교,기존(원)교,030-25,서울특별시 종로구 통일로12길 23 (무악동),서울특별시 종로구
9143,초등학교,초등학교,서울,중부,종로구,서울매동초등학교,본교,기존(원)교,030-27,서울특별시 종로구 사직로9길 19 . 서울매동초등학교 (필운동),서울특별시 종로구

In [35]:
# 외부 법정동 테이블의 전체 행 개수가 229개이므로 유치원 법정동 개수도 같은지 확인 : 그래야 테이블끼리 제대로 조인 할수 있음
s_primary.groupby(['법정동']).count()

           학제  학교 세부 유형   시도  교육지원청  행정구  학교명  본분교  학교상태  우편번호  도로명주소
법정동
강원도 강릉시    39        39   39     39   39   39   39    39    39     39
강원도 고성군    11        11   11     11   11   11   11    11    11     11
강원도 동해시    17        17   17     17   17   17   17    17    17     17
강원도 삼척시    17        17   17     17   17   17   17    17    17     17
강원도 속초시    11        11   11     11   11   11   11    11    11     11
...       ...       ...  ...    ...  ...  ...  ...   ...   ...    ...
충청북도 제천시   35        35   35     35   35   35   35    35    35     35
충청북도 증평군    5         5    5      5    5    5    5     5     5      5
충청북도 진천군   17        17   17     17   17   17   17    17    17     17
충청북도 청주시  144       144  144    144  144  144  144   144   144    144
충청북도 충주시   46        46   46     46   46   46   46    46    46     46

[229 rows x 10 columns]

In [36]:
# 초등학교 테이블도 동일하게 확인
s_elementary.groupby(['법정동']).count()

          학제  학교 세부 유형  시도  교육지원청  행정구  학교명  본분교  학교상태  우편번호  도로명주소
법정동
강원도 강릉시   37        37  37     37   37   37   37    37    37     37
강원도 고성군   15        15  15     15   15   15   15    15    15     15
강원도 동해시   14        14  14     14   14   14   14    14    14     14
강원도 삼척시   20        20  20     20   20   20   20    20    20     20
강원도 속초시   12        12  12     12   12   12   12    12    12     12
...       ..       ...  ..    ...  ...  ...  ...   ...   ...    ...
충청북도 제천시  24        24  24     24   24   24   24    24    24     24
충청북도 증평군   4         4   4      4    4    4    4     4     4      4
충청북도 진천군  16        16  16     16   16   16   16    16    16     16
충청북도 청주시  98        98  98     98   98   98   98    98    98     98
충청북도 충주시  39        39  39     39   39   39   39    39    39     39

[229 rows x 10 columns]

In [73]:
s_2.groupby(['법정동']).count()

          학제  학교 세부 유형  고등학교유형  시도  교육지원청  행정구  학교명  본분교  학교상태  우편번호  도로명주소
법정동
강원도 강릉시   24        24      11  24     24   24   24   24    24    24     24
강원도 고성군    8         8       4   8      8    8    8    8     8     8      8
강원도 동해시   13        13       6  13     13   13   13   13    13    13     13
강원도 삼척시   21        21       9  21     21   21   21   21    21    21     21
강원도 속초시    8         8       3   8      8    8    8    8     8     8      8
...       ..       ...     ...  ..    ...  ...  ...  ...   ...   ...    ...
충청북도 제천시  22        22       7  22     22   22   22   22    22    22     22
충청북도 증평군   6         6       3   6      6    6    6    6     6     6      6
충청북도 진천군  13        13       6  13     13   13   13   13    13    13     13
충청북도 청주시  88        88      37  88     88   88   88   88    88    88     88
충청북도 충주시  33        33      11  33     33   33   33   33    33    33     33

[229 rows x 11 columns]

In [37]:
# 외부 테이블 불러옴
df = pd.read_csv('../Data/법정동_Data/법정동코드_최종본.csv')

In [74]:
df

     Unnamed: 0       법정동코드          법정동명 폐지여부
0             0  1111000000     서울특별시 종로구   존재
1             1  1114000000      서울특별시 중구   존재
2             2  1117000000     서울특별시 용산구   존재
3             3  1120000000     서울특별시 성동구   존재
4             4  1121500000     서울특별시 광진구   존재
..          ...         ...           ...  ...
224         224  4887000000      경상남도 함양군   존재
225         225  4888000000      경상남도 거창군   존재
226         226  4889000000      경상남도 합천군   존재
227         227  5011000000   제주특별자치도 제주시   존재
228         228  5013000000  제주특별자치도 서귀포시   존재

[229 rows x 4 columns]

In [70]:
# 법정동 이름이 서로 안맞는지 확인해 보기 위해 set으로 변화 set으로만 차집합, 합집합 함수 사용 가능
set1= set(df['법정동명'])
set2=set(s_2['법정동'])

In [71]:
# 각자 차집합 확인
complement = set2 - set1
complement2 = set1 - set2

In [72]:
# 다른게 나오면 위의 하나하나 고쳐주던 코드에서 붙여서 이름 맞추어 변경 - 없으면 제대로 이름 다 맞춰진 것. 
complement
complement

set()

set()