In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 전체 코드 출력
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [9]:
# 한글 문제
# matplotlit의 기본 폰트에서 한글 지원되지 않기 때문에
# matplotlib의 폰트 변경 필요
import platform

from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':  # 맥OS 
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':  # 윈도우
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system...  sorry~~~')

In [10]:
school_data = pd.read_excel('../Data/학교_Data/1. 유·초·중등교육기관 주소록(2018).xlsx', header=3)
school_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21342 entries, 0 to 21341
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   연도        21342 non-null  int64
 1   학제        21342 non-null  object
 2   학교 세부 유형  21342 non-null  object
 3   고등학교유형    2365 non-null   object
 4   시도        21342 non-null  object
 5   교육지원청     21342 non-null  object
 6   행정구       21342 non-null  object
 7   학교명       21342 non-null  object
 8   본분교       21342 non-null  object
 9   학교상태      21342 non-null  object
 10  설립        21342 non-null  object
 11  남여공학      5871 non-null   object
 12  우편번호      21342 non-null  object
 13  도로명주소     21342 non-null  object
 14  연락처       21342 non-null  object
 15  팩스번호      21341 non-null  object
 16  홈페이지      20240 non-null  object
dtypes: int64(1), object(16)
memory usage: 2.8+ MB

In [11]:
school_data.drop(school_data.columns[[0,10,11,14,15,16]],axis=1, inplace=True)

In [12]:
ind=[]
for i in range(len(school_data)):
    if school_data['도로명주소'][i].split(' ')[0]== '세종특별자치시' :
        ind.append(school_data['도로명주소'][i].split(' ')[0])
    elif school_data['도로명주소'][i].split(' ')[0]== '서울' :
         ind.append('서울특별시 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '경기' :
         ind.append('경기도 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '경남' :
         ind.append('경상남도 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '대구' :
         ind.append('대구광역시 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '충북' :
         ind.append('충청북도 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '인천' :
         ind.append('인천광역시 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '강원' :
         ind.append('강원도 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '경북' :
         ind.append('경상북도 ' +school_data['도로명주소'][i].split(' ')[1])
    elif school_data['도로명주소'][i].split(' ')[0]== '전북' :
         ind.append('전라북도 ' +school_data['도로명주소'][i].split(' ')[1])
    else :
         ind.append(' '.join(school_data['도로명주소'][i].split(' ')[:2]))

school_data['법정동']=ind
school_data

,학제,학교 세부 유형,고등학교유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소,법정동
0,유치원,유치원,NaN,서울,중부,종로구,린덴바움유치원,본교,기존(원)교,030-25,서울특별시 종로구 통일로12길 51 . 린덴바움유치원 (무악동),서울특별시 종로구
1,유치원,유치원,NaN,서울,중부,종로구,배화여자대학교 부속 배화유치원,본교,기존(원)교,030-39,서울특별시 종로구 필운대로1길 34 (필운동),서울특별시 종로구
2,유치원,유치원,NaN,서울,중부,종로구,봄샘유치원,본교,기존(원)교,031-24,서울특별시 종로구 율곡로 264 (종로6가.서울복음교회),서울특별시 종로구
3,유치원,유치원,NaN,서울,중부,종로구,상명사대부속유치원,본교,기존(원)교,030-15,서울특별시 종로구 홍지문2길 1 . 상명사대부속유치원 (홍지동),서울특별시 종로구
4,유치원,유치원,NaN,서울,중부,종로구,서울명신초등학교병설유치원,본교,기존(원)교,030-93,서울특별시 종로구 낙산길 250 (창신동. 서울명신초등학교),서울특별시 종로구
...,...,...,...,...,...,...,...,...,...,...,...,...
21337,각종학교,각종학교(고교),NaN,경남,경남,창원시,창원예술학교,본교,신설(원)교,512-03,경상남도 창원시 마산회원구 구암북12길 24 (구암동),경상남도 창원시
21338,각종학교,각종학교(중학),NaN,경남,경남,진주시,경남꿈키움중학교,본교,기존(원)교,526-15,경상남도 진주시 이반성면 길성길 1-80 (이반성면),경상남도 진주시
21339,각종학교,각종학교(고교),NaN,경남,경남,밀양시,밀양영화고등학교,본교,기존(원)교,504-53,경상남도 밀양시 상남면 평촌중앙로 61-6 (상남면),경상남도 밀양시
21340,각종학교,각종학교(고교),NaN,경남,경남,고성군,경남고성음악고등학교,본교,기존(원)교,529-56,경상남도 고성군 하일면 공룡로 987 (하일면),경상남도 고성군
21341,각종학교,각종학교(중학),NaN,경남,경남,하동군,지리산중학교,본교,기존(원)교,523-09,경상남도 하동군 청암면 삼신봉로 110-8 . 지리산중학교 (청암면),경상남도 하동군

In [13]:
# 외부 법정동 테이블과 연결을 위해 이름이 다른 것들 찾아서 각각 지정
school_data.loc[school_data.법정동=='경남 창원시', "법정동"] = '경상남도 창원시'
school_data.loc[school_data.법정동=='경북 영천시', "법정동"] = '경상북도 영천시'
school_data.loc[school_data.법정동=='경북 영천시', "법정동"] = '경상북도 영천시'
school_data.loc[school_data.법정동=='구로구 고척로', "법정동"] = '서울특별시 구로구'
school_data.loc[school_data.법정동=='부산 사상구', "법정동"] = '부산광역시 사상구'
school_data.loc[school_data.법정동=='서울시 구로구', "법정동"] = '서울특별시 구로구'
school_data.loc[school_data.법정동=='익산시 평동로', "법정동"] = '전라북도 익산시'
school_data.loc[school_data.법정동=='인천광역시 남구', "법정동"] = '인천광역시 미추홀구'
school_data.loc[school_data.법정동=='화성시 향남읍', "법정동"] = '경기도 화성시'
school_data.loc[school_data.법정동=='경남 사천시', "법정동"] = '경상남도 사천시'
school_data.loc[school_data.법정동=='광주 광산구', "법정동"] = '광주광역시 광산구'
school_data.loc[school_data.법정동== '전남 장성군', "법정동"] = '전라남도 장성군'

In [14]:
# 중학교, 고등00학교 테이블을 따로 나누기 위해 각 학제별 카운트
school_data.groupby(['학제']).count()

,학교 세부 유형,고등학교유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소,법정동
학제,,,,,,,,,,,
각종학교,60,0,60,60,60,60,60,60,60,60,60
고등공민학교,3,0,3,3,3,3,3,3,3,3,3
고등기술학교,7,0,7,7,7,7,7,7,7,7,7
고등학교,2365,2365,2365,2365,2365,2365,2365,2365,2365,2365,2365
유치원,9164,0,9164,9164,9164,9164,9164,9164,9164,9164,9164
중학교,3260,0,3260,3260,3260,3260,3260,3260,3260,3260,3260
초등학교,6307,0,6307,6307,6307,6307,6307,6307,6307,6307,6307
특수학교,176,0,176,176,176,176,176,176,176,176,176

In [15]:
school_data.groupby(['학교 세부 유형']).count()

,학제,고등학교유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소,법정동
학교 세부 유형,,,,,,,,,,,
가사고등학교,30,30,30,30,30,30,30,30,30,30,30
각종학교(고교),24,0,24,24,24,24,24,24,24,24,24
각종학교(중학),19,0,19,19,19,19,19,19,19,19,19
각종학교(중학+고교),9,0,9,9,9,9,9,9,9,9,9
각종학교(초등),2,0,2,2,2,2,2,2,2,2,2
각종학교(초등+중학),3,0,3,3,3,3,3,3,3,3,3
각종학교(초등+중학+고교),3,0,3,3,3,3,3,3,3,3,3
고등공민학교,3,0,3,3,3,3,3,3,3,3,3
고등기술학교,7,0,7,7,7,7,7,7,7,7,7
공업고등학교,230,230,230,230,230,230,230,230,230,230,230
과학고등학교,28,28,28,28,28,28,28,28,28,28,28
국제고등학교,7,7,7,7,7,7,7,7,7,7,7
국제중학교,5,0,5,5,5,5,5,5,5,5,5
기타학교(특수),149,0,149,149,149,149,149,149,149,149,149
농림업고등학교,45,45,45,45,45,45,45,45,45,45,45
농아학교(특수),14,0,14,14,14,14,14,14,14,14,14
대안고등학교,2,2,2,2,2,2,2,2,2,2,2
맹아학교(특수),13,0,13,13,13,13,13,13,13,13,13
상업고등학교,182,182,182,182,182,182,182,182,182,182,182
수산고등학교,9,9,9,9,9,9,9,9,9,9,9
실업고등학교,23,23,23,23,23,23,23,23,23,23,23
예술고등학교,29,29,29,29,29,29,29,29,29,29,29
예술중학교,3,0,3,3,3,3,3,3,3,3,3
외국어고등학교,31,31,31,31,31,31,31,31,31,31,31
유치원,9164,0,9164,9164,9164,9164,9164,9164,9164,9164,9164
일반고등학교,1682,1682,1682,1682,1682,1682,1682,1682,1682,1682,1682
일반중학교,3241,0,3241,3241,3241,3241,3241,3241,3241,3241,3241
종합고등학교,48,48,48,48,48,48,48,48,48,48,48
체육고등학교,17,17,17,17,17,17,17,17,17,17,17
체육중학교,11,0,11,11,11,11,11,11,11,11,11
초등학교,6307,0,6307,6307,6307,6307,6307,6307,6307,6307,6307
해양고등학교,2,2,2,2,2,2,2,2,2,2,2

In [16]:
s_4 = school_data.loc[(school_data['학제']=='고등학교')] # 각종학교 / 고등공민학교 / 고등기술학교는 어떻게 할지 고민 중
s_4

,학제,학교 세부 유형,고등학교유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소,법정동
18731,고등학교,상업고등학교,특성화고(직업),서울,서울시,종로구,경기상업고등학교,본교,기존(원)교,030-47,서울특별시 종로구 자하문로 136 (청운동),서울특별시 종로구
18732,고등학교,일반고등학교,일반고,서울,서울시,종로구,경복고등학교,본교,기존(원)교,030-47,서울특별시 종로구 자하문로28가길 9 . 경복고등학교 (청운동.경복고등학교),서울특별시 종로구
18733,고등학교,일반고등학교,일반고,서울,서울시,종로구,경신고등학교,본교,기존(원)교,030-67,서울특별시 종로구 혜화로 74 (혜화동.경신중고등학교),서울특별시 종로구
18734,고등학교,상업고등학교,특성화고(직업),서울,서울시,종로구,대동세무고등학교,본교,기존(원)교,030-57,서울특별시 종로구 계동길 84-10 . 대동세무고등학교 (계동),서울특별시 종로구
18735,고등학교,일반고등학교,일반고,서울,서울시,종로구,대신고등학교,본교,기존(원)교,030-29,서울특별시 종로구 사직로 9 (행촌동),서울특별시 종로구
...,...,...,...,...,...,...,...,...,...,...,...,...
21091,고등학교,농림업고등학교,특성화고(직업),제주,제주,서귀포시,서귀포산업과학고등학교,본교,기존(원)교,635-82,제주특별자치도 서귀포시 516로 501 . 서귀포산업과학고등학교 (상효동),제주특별자치도 서귀포시
21092,고등학교,일반고등학교,일반고,제주,제주,서귀포시,서귀포여자고등학교,본교,기존(원)교,635-71,제주특별자치도 서귀포시 태평로 80 (호근동.서귀포여자고등학교),제주특별자치도 서귀포시
21093,고등학교,수산고등학교,일반고,제주,제주,서귀포시,성산고등학교,본교,기존(원)교,636-39,제주특별자치도 서귀포시 성산읍 한도로 79-17 . 성산고등학교 (성산읍),제주특별자치도 서귀포시
21094,고등학교,가사고등학교,특성화고(직업),제주,제주,서귀포시,중문고등학교,본교,기존(원)교,635-40,제주특별자치도 서귀포시 일주서로570번길 19 (대포동),제주특별자치도 서귀포시
21095,고등학교,일반고등학교,일반고,제주,제주,서귀포시,표선고등학교,본교,기존(원)교,636-29,제주특별자치도 서귀포시 표선면 표선중앙로 22-15 (표선면.표선고등학교),제주특별자치도 서귀포시

In [17]:
s_3 = school_data.loc[(school_data['학제']=='중학교')]
s_3.groupby('학교상태').count()

,학제,학교 세부 유형,고등학교유형,시도,교육지원청,행정구,학교명,본분교,우편번호,도로명주소,법정동
학교상태,,,,,,,,,,,
기존(원)교,3215,3215,0,3215,3215,3215,3215,3215,3215,3215,3215
신설(원)교,18,18,0,18,18,18,18,18,18,18,18
폐(원)교,24,24,0,24,24,24,24,24,24,24,24
휴(원)교,3,3,0,3,3,3,3,3,3,3,3

In [18]:
s_3.drop('고등학교유형', axis=1, inplace=True)
s_3

C:\Users\ksj14\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,학제,학교 세부 유형,시도,교육지원청,행정구,학교명,본분교,학교상태,우편번호,도로명주소,법정동
15471,중학교,일반중학교,서울,중부,종로구,경신중학교,본교,기존(원)교,030-67,서울특별시 종로구 혜화로 74 (혜화동.경신중고등학교),서울특별시 종로구
15472,중학교,일반중학교,서울,중부,종로구,대신중학교,본교,기존(원)교,030-29,서울특별시 종로구 사직로 9 (행촌동),서울특별시 종로구
15473,중학교,일반중학교,서울,중부,종로구,덕성여자중학교,본교,기존(원)교,030-62,서울특별시 종로구 율곡로3길 49 (송현동),서울특별시 종로구
15474,중학교,일반중학교,서울,중부,종로구,동성중학교,본교,기존(원)교,030-83,서울특별시 종로구 대학로 156 동성중학교 (혜화동90-7),서울특별시 종로구
15475,중학교,일반중학교,서울,중부,종로구,배화여자중학교,본교,기존(원)교,030-27,서울특별시 종로구 필운대로1길 34 배화여자중학교,서울특별시 종로구
...,...,...,...,...,...,...,...,...,...,...,...
18726,중학교,일반중학교,제주,서귀포시,서귀포시,안덕중학교,본교,기존(원)교,635-30,제주특별자치도 서귀포시 안덕면 화순로 74 (안덕면),제주특별자치도 서귀포시
18727,중학교,일반중학교,제주,서귀포시,서귀포시,위미중학교,본교,기존(원)교,636-09,제주특별자치도 서귀포시 남원읍 위미상원북로 34 (남원읍),제주특별자치도 서귀포시
18728,중학교,일반중학교,제주,서귀포시,서귀포시,중문중학교,본교,기존(원)교,635-46,제주특별자치도 서귀포시 천제연로232번길 10 (중문동),제주특별자치도 서귀포시
18729,중학교,일반중학교,제주,서귀포시,서귀포시,표선중학교,본교,기존(원)교,636-29,제주특별자치도 서귀포시 표선면 표선중앙로 31 . 표선중학교 (표선면),제주특별자치도 서귀포시
18730,중학교,일반중학교,제주,서귀포시,서귀포시,효돈중학교,본교,기존(원)교,636-06,제주특별자치도 서귀포시 효돈로 207 . 효돈중학교 (하효동),제주특별자치도 서귀포시

In [19]:
s_3.to_csv("../Data/학교_Data/중학교_유형_주소(2018).csv")

In [20]:
s_4.to_csv("../Data/학교_Data/고등학교_유형_주소(2018).csv")

In [21]:
# found = school_data.index('고등학교')  # 리스트 형태로 바꾼 뒤에야 .index() 메소드를 쓸 수 있는 모양인데 복잡해서 포기
# found