In [11]:
import pandas as pd

In [12]:
sub =pd.read_csv('최종본_전국지하철역목록.csv' index_col=None)

SyntaxError: invalid syntax (<ipython-input-12-3f1b65ae9a06>, line 1)

In [13]:
sub[sub.duplicated(['역사명'])]

,Unnamed: 0,역번호,역사명,노선번호,노선명,환승역구분,환승노선번호,환승노선명,역위도,역경도,주소,시도코드,시군구코드,법정동코드
11,11,0201,시청,S1102,서울 도시철도 2호선,환승역,S1101,서울 도시철도 1호선,37.564619,126.976086,서울특별시 중구,11,11020,1114000000
56,56,0246,신설동,S1102,서울 도시철도 2호선,환승역,S1101,서울 도시철도 1호선+우의신설,37.575196,127.024858,서울특별시 동대문구,11,11060,1123000000
71,71,0319,종로3가,S1103,서울 도시철도 3호선,환승역,S1101+S1105,서울 도시철도 1호선+서울 도시철도 6호선,37.571394,126.991411,서울특별시 종로구,11,11010,1111000000
72,72,0320,을지로3가,S1103,서울 도시철도 3호선,환승역,S1102,서울 도시철도 2호선,37.566348,126.991482,서울특별시 중구,11,11020,1114000000
82,82,0330,교대,S1103,서울 도시철도 3호선,환승역,S1103,서울 도시철도 3호선,37.493201,127.014024,서울특별시 서초구,11,11220,1165000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,U123,어룡,L4101,의정부경전철,일반역,-,-,37.742696,127.085226,경기도 의정부시,31,31030,4115000000
997,997,U124,송산,L4101,의정부경전철,일반역,NaN,NaN,37.737262,127.087226,경기도 의정부시,31,31030,4115000000
999,999,U125,탑석,L4101,의정부경전철,일반역,-,-,37.733467,127.088928,경기도 의정부시,31,31030,4115000000
1000,1000,Y110,기흥역,T4101,에버라인,환승역,K237,기흥역,37.275657,127.115944,경기도 용인시,31,31191,4146000000
1004,1004,Y114,동백역,T4101,에버라인,일반역,NaN,NaN,37.269111,127.152716,경기도 용인시,31,31191,4146000000