In [45]:
import pandas as pd

In [46]:
bars = pd.read_csv("../Data/주변환경_Data/수정본_유흥업소지역별현황.csv")

In [47]:
region_code = pd.read_csv("../Data/법정동_Data/법정동코드 전체자료.csv",encoding='cp949',sep='\t')

In [48]:
idx = []
for i in range(len(region_code)):
    if len(region_code.법정동명[i].split(' '))<=2:
        idx.append(i)

In [52]:
region_code = region_code.iloc[idx]

In [55]:
region_code.reset_index(drop=True, inplace=True)

In [56]:
idx = []
for i in range(len(region_code)):
    if len(region_code.법정동명[i].split(' '))==1:
        idx.append(i)

In [57]:
region_code.iloc[idx]

          법정동코드     법정동명 폐지여부
0    1100000000    서울특별시   존재
26   2100000000    부산직할시   폐지
39   2200000000    대구직할시   폐지
47   2300000000    인천직할시   폐지
54   2400000000    광주직할시   폐지
59   2500000000    대전직할시   폐지
65   2600000000    부산광역시   존재
82   2700000000    대구광역시   존재
91   2800000000    인천광역시   존재
104  2900000000    광주광역시   존재
110  3000000000    대전광역시   존재
116  3100000000    울산광역시   존재
122  3611000000  세종특별자치시   존재
147  4100000000      경기도   존재
200  4200000000      강원도   존재
226  4300000000     충청북도   존재
243  4400000000     충청남도   존재
273  4500000000     전라북도   존재
296  4600000000     전라남도   존재
329  4700000000     경상북도   존재
369  4800000000     경상남도   존재
411  4900000000      제주도   폐지
416  5000000000  제주특별자치도   존재

In [58]:
region_code.법정동명

          법정동코드          법정동명 폐지여부
0    1100000000         서울특별시   존재
1    1111000000     서울특별시 종로구   존재
2    1114000000      서울특별시 중구   존재
3    1117000000     서울특별시 용산구   존재
4    1120000000     서울특별시 성동구   존재
..          ...           ...  ...
414  4971000000      제주도 북제주군   폐지
415  4972000000      제주도 남제주군   폐지
416  5000000000       제주특별자치도   존재
417  5011000000   제주특별자치도 제주시   존재
418  5013000000  제주특별자치도 서귀포시   존재

[419 rows x 3 columns]

In [59]:
region_code.loc[region_code['법정동명'].str.contains('세종'),:]

          법정동코드          법정동명 폐지여부
122  3611000000       세종특별자치시   존재
123  3611010100   세종특별자치시 반곡동   존재
124  3611010200   세종특별자치시 소담동   존재
125  3611010300   세종특별자치시 보람동   존재
126  3611010400   세종특별자치시 대평동   존재
127  3611010500   세종특별자치시 가람동   존재
128  3611010600   세종특별자치시 한솔동   존재
129  3611010700   세종특별자치시 나성동   존재
130  3611010800   세종특별자치시 새롬동   존재
131  3611010900   세종특별자치시 다정동   존재
132  3611011000   세종특별자치시 어진동   존재
133  3611011100   세종특별자치시 종촌동   존재
134  3611011200   세종특별자치시 고운동   존재
135  3611011300   세종특별자치시 아름동   존재
136  3611011400   세종특별자치시 도담동   존재
137  3611025000  세종특별자치시 조치원읍   존재
138  3611031000   세종특별자치시 연기면   존재
139  3611032000   세종특별자치시 연동면   존재
140  3611033000   세종특별자치시 부강면   존재
141  3611034000   세종특별자치시 금남면   존재
142  3611035000   세종특별자치시 장군면   존재
143  3611036000   세종특별자치시 연서면   존재
144  3611037000   세종특별자치시 전의면   존재
145  3611038000   세종특별자치시 전동면   존재
146  3611039000   세종특별자치시 소정면   존재